services:
  - type: web
    name: messenger
    env: python
    plan: free
    pythonVersion: 3.11.7
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 -b 0.0.0.0:8080 --timeout 120 app:app
